### ISSUE TITLE
Option to disable animations in Sterling

### ISSUE THREAD

**Issue by rgreenblatt** [cemcutting/Forge#11]
Clicking through too fast causes display bugs and the animations generally get in the way.
![animation_bug](https://user-images.githubusercontent.com/8813096/74188659-e6036980-4c1c-11ea-9497-d2a676151ff6.png)
For example, in the above image, Node7 is connected to Node2 (confirmed using the evaluator), but the graphic is wrong. This was caused by rapidly clicking through. 

Ideally the option wouldn't need to be set each time a new instance is opened.

**Comment by MLavrentyev** [comment]
New sterling no longer has animations - I'm closing this issue since it seems to no longer be a problem.
