### ISSUE TITLE
Kodkod CLI shut down unexpectedly! (running anything)

### ISSUE THREAD

**Issue by yutong-liang** [cemcutting/Forge#15]
Hi,

So far forge has not been able to run anything on my laptop - when I click "run" on any file, no browser window pops up and it gives the error "Kodkod CLI shut down unexpectedly!". I have updated forge to the latest version, but nothing has changed.

Dr.Racket version: 7.5

Java version: java version "1.6.0_65" , Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468), Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

OS: macOS High Sierra 10.13.6, 64 bit

spec: everything

Thank you!

**Comment by cemcutting** [comment]
I believe this is a Java versioning issue - can you install Java 7 or 8 (Java downloads can be found here: https://www.java.com/en/download/) and try again?  Please let me know if the issue persists!

**Comment by yutong-liang** [comment]
Yes works now! Thank you so much!
