### ISSUE TITLE
Function application with join has wrong precedence

### ISSUE THREAD

**Issue by MLavrentyev** [cemcutting/Forge#16]
When you have a function application followed by a join, it has the wrong precedence, so
```alloy
sing[1].succ
```
throws an error, but if we add parens, it doesn't:
```alloy
(sing[1]).succ
```
Ideally the precedence would be such that we didn't need to do that. (might be a box join sideeffect?)

**Comment by asvarga** [comment]
This was because dot join binds stronger than box join, and function application parses like a box join. Good catch.
