### ISSUE TITLE
Incorrect Web Browser to Open Sterling In

### ISSUE THREAD

**Issue by david-boles** [cemcutting/Forge#23]
I had to reinstall forge and it now doesn't open Sterling properly, it instead starts up a particular standalone app on my system (which might be built with Electron or similar). I'm running (out of date) Debian sid (unstable), and everything that [this page](https://wiki.debian.org/DefaultWebBrowser) mentions points correctly to Firefox or Chromium. Any ideas?

**Comment by MLavrentyev** [comment]
Can you post your Forge version, OS + exact version you're runnning, java version, and the settings you've set? It'll help us reproduce. Thanks!

**Comment by david-boles** [comment]
I tried reinstalling DrRacket to fix this (removed with the uninstall script, reinstalled 7.6) and haven't set any settings other than installing forge (0.0.15 at the time), and it was still occurring. I'm not sure how to be more specific about my OS unfortunately, it's a fairly clean Debian sid installation, updated sometime last semester probably. I'm running OpenJDK 11.0.6 as well as Xorg (instead of Wayland) if that could affect things.

**Comment by sorawee** [comment]
Note: DrRacket has a separate browser preference for Unix at Preferences > Browser. Try editing the configuration?

**Comment by MLavrentyev** [comment]
> 
> 
> Note: DrRacket has a separate browser preference for Unix at Preferences > Browser. Try editing the configuration?

That might be it - I remember reading something about this but couldn't reproduce since I'm running on Windows :/

**Comment by MLavrentyev** [comment]
Although I can't seem to find a "preferences" menu. Where is that found? @sorawee

**Comment by sorawee** [comment]
As I understand, it's only available for Unix systems, appearing before the "HTTP Proxy" section. MacOS and Windows will only have "HTTP Proxy" section.

<img width="391" alt="Screen Shot 2020-02-26 at 12 05 07" src="https://user-images.githubusercontent.com/9099577/75382989-60c0bb80-5890-11ea-90f1-2b27139a4e63.png">

Here's the relevant code that creates the preference window: https://github.com/racket/drracket/blob/b8770e115895a4f5c592f514b2b66d7255603bfb/drracket/browser/external.rkt#L163

**Comment by sorawee** [comment]
> Although I can't seem to find a "preferences" menu.

Ah, sorry. I misunderstood your question.

The preference window can be found at "DrRacket > Preferences" on MacOS, and "Edit > Preferences" on Unix. I don't know about Windows, but it should be something similar.

**Comment by MLavrentyev** [comment]
Awesome, thank you so much for the help!

**Comment by david-boles** [comment]
@MLavrentyev Just tested, worked for me! Would it make sense to file this as a Racket/ DrRacket issue?

**Comment by MLavrentyev** [comment]
I'm guessing it's not an issue per-se since they likely intentionally implemented that way, but a bad feature nonetheless. Up to you, but if want to do so, here's the link: https://github.com/racket/drracket/issues
