### ISSUE TITLE
Move documentation to wiki/scribble

### ISSUE THREAD

**Issue by MLavrentyev** [cemcutting/Forge#30]
Move the docs to some other more visible place than some markdown files in a branch of the repo. Options include either the built-in repo wiki on the github or scribble, which would integrate nicely with the default racket docs.

**Comment by asvarga** [comment]
The wiki seems pretty easy; we'd just have to move the files and fix the links. What are the pros of going with scribble? We won't have lots of links to racket documentation or anything.

**Comment by asvarga** [comment]
Also, if you do this, note that `dev` has some docs updates that aren't in `master` at the moment.

**Comment by asvarga** [comment]
I've moved the docs to the wiki. Let me know what you think @MLavrentyev.

**Comment by MLavrentyev** [comment]
Looks good! I'll close this issue for now. The scribble has the pro of showing up in the official racket docs when you search there (since it takes scribble docs from the package manager). Cons are that it kinda looks worse (eventually, it'll probably need to happen). Thanks again!
