### ISSUE TITLE
Kodkod CLI shut down unexpectedly! when running for exactly 0

### ISSUE THREAD

**Issue by rgreenblatt** [cemcutting/Forge#6]
```
sig Atom {edges: set Atom}

run {} for exactly 0 Atom
```
Doesn't fail if run for exactly 1 Atom or without the edges set.

**Comment by MLavrentyev** [comment]
Just ran this - seems to be working as expected. Is this still an issue @rgreenblatt ? If not, I'll close this.

**Comment by rgreenblatt** [comment]
Yep, works!
